[tool.coverage.run]
source = ["inorbit_connector/", "tests/"]

[tool.flake8]
exclude = [".venv/", ".tox/"]
max-line-length = 88
show-source = true
statistics = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
