name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test 🔍
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv pip install -e ".[dev]"
    - name: Test with tox
      run: uv run tox

  # TODO: Fix issues and then uncomment
  # NOTE: To fix (this should be added to CONTRIBUTING.md)
  # - Lint: `reuse --root . lint`
  # - Fix `reuse annotate --copyright "InOrbit, Inc." --license "MIT" --recursive . --skip-unrecognised`
  # reuse-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: REUSE Compliance Check
  #       uses: fsfe/reuse-action@v1
